# Straight from:
# https://github.com/ThePrimeagen/fem-algos/blob/main/.github/workflows/next.yaml
# by [ThePrimeagen](https://github.com/ThePrimeagen)

name: Deploy NextJS build to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install, export
        run: |
          cd app
          npm install
          npm run build
      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: app/out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
